/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCronRefreshCacheRouteImport } from './routes/api/cron/refresh-cache'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshCacheRoute = ApiCronRefreshCacheRouteImport.update({
  id: '/api/cron/refresh-cache',
  path: '/api/cron/refresh-cache',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron/refresh-cache': typeof ApiCronRefreshCacheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron/refresh-cache': typeof ApiCronRefreshCacheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron/refresh-cache': typeof ApiCronRefreshCacheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cron/refresh-cache'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cron/refresh-cache'
  id: '__root__' | '/' | '/api/cron/refresh-cache'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronRefreshCacheRoute: typeof ApiCronRefreshCacheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh-cache': {
      id: '/api/cron/refresh-cache'
      path: '/api/cron/refresh-cache'
      fullPath: '/api/cron/refresh-cache'
      preLoaderRoute: typeof ApiCronRefreshCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronRefreshCacheRoute: ApiCronRefreshCacheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
